---
title: "Presentación del curso"
subtitle: "¿Qué aprenderemos y cómo?"
author: "Daniel Jiménez M."
date: "`r format(Sys.time(), '%d -%m -%Y')`"
institute: "Universidad Nacional de Colombia"
output: 
  beamer_presentation:
    theme: "Madrid"
    colortheme: "beaver"
    #incremental: true
    slide_level: 2
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Contenido 

* ¿Qué aprenderemos en este curso?
* ¿Dónde se encuentra el material del curso?
* ¿Dónde se subirá el trabajo del curso?
* Reglas de la clase
* Presentación de los participantes
* Contacto con el profesor


## ¿Qué aprenderemos en este curso?

La idea principal del curso es dotarle al participante de todas las herramientas necesarias para que pueda aborar soluciones a problemas con datos de la manera más oportuna y es por ello que este curso tendrá un enfoqué dividido en tres partes: 

* Ciencia: Estádistica aplicada al análisis exploratorio de datos;
* Tecnología: Github para el manejo de versionamiento del trabajo
* Aplicación: Trabajaremos con bases de datos de la vida real, la mayoría de Kaggle y un último ejercicio con una base de datos de la JEP


## ¿Qué aprenderemos en este curso?

1. Introducción al manejo de git y github
2. Introducción a Python
3. Statistical Thinking en Python
4. Modelamiento estadístico para el caso de textos


## ¿Dónde se encuentra el material del curso?

URL : https://github.com/carlosjimenez88M/EDA_Course


## ¿Dónde se subirá el trabajo del curso?

Existe una carpeta dentro del repositorio, donde subiremos el trabajo individual y el grupal que desarrollaremos durantes las clases.

## Reglas de la clase

* Se tomará lista 20 minutos antes de terminar la clase
* Se desarrollaran proyectos en grupo cada semana 
* Cualquier inquietud puede contactar al profesor y este mismo tendrá un plazo de 48 horas para responder vía mail (menos los fines de semana)



##  Presentación de los participantes

Por favor presentese bajo los siguientes parámetros:

* Nombre;

* ¿A qué se dedica?;

* Un hobbie;

* Algo que rompa el hielo.

## Contacto con el profesor

* __Mail:__ danieljimenez88m@gmail.com
* __Web:__ www.danieljimenezm.com
* __Github:__ carlosjimenez88M

